import java.nio.file.Path;
import java.nio.file.Paths;

public class TeXBuilder {

    private static final String DEFAULT_OUTPUT_FILE_NAME = "output";

    private boolean log; /* Should the TeXBuilder keep the log file generated by TeX? */
    private boolean dvi; /* Should the TeXBuilder keep the dvi file generated by TeX? */
    private boolean pdf; /* Should the TeXBuilder generate a pdf file? */
    private String outputFileName; /* The name of the file generated by TeX (Excluding file extensions) */
    private Path outputFilePath; /* The path to the file generated by TeX (Excluding the file itself) */

    /**
     * Default Constructor
     * Creates a TeXBuilder that generates a pdf file titled "out.pdf" in the JRE working directory
     */
    public TeXBuilder(){
        this.log = false;
        this.dvi = false;
        this.pdf = true;
        this.outputFileName = DEFAULT_OUTPUT_FILE_NAME;
        this.outputFilePath = getDefaultOutputFilePath();
    }

    /**
     * Customized Constructor
     * @param log Should the TeXBuilder keep the log file generated by TeX?
     * @param dvi Should the TeXBuilder keep the dvi file generated by TeX?
     * @param pdf Should the TeXBuilder generate and a pdf file?
     * @param outputFileName The name of the file generated by TeX (Excluding file extensions).
     * @param outputFilePath The path to the file generated by TeX (Excluding the file itself).
     */
    public TeXBuilder(boolean log, boolean dvi, boolean pdf, String outputFileName, Path outputFilePath){
        this.log = log;
        this.dvi = dvi;
        this.pdf = pdf;
        /* Check that the given outputFileName and outputFilePath are valid. Assign default values if invalid */
        this.outputFileName = validFileName(outputFileName) ? outputFileName : DEFAULT_OUTPUT_FILE_NAME;
        this.outputFilePath = validFilePath(outputFilePath) ? outputFilePath : getDefaultOutputFilePath();
    }

    /**
     * @return A Path object representing the default file path of the JRE.
     */
    private Path getDefaultOutputFilePath(){
        return Paths.get("");
    }

    /**
     * This function determines if the given name is a valid file name on this system.
     * @param name The file name to be checked.
     * @return A boolean indicating whether the name is a valid file name.
     */
    private boolean validFileName(String name){
        /*
         * A file name is valid if the Path object created with it is not null
         * (The path Class will not construct invalid path objects).
         */
        return Paths.get(name) != null;
    }

    /**
     * This function determines if the given path is a valid file path on this system.
     * @param path The path to be checked.
     * @return A boolean indicating whether the name is a valid file name.
     */
    private boolean validFilePath(Path path){
        /*
         * A path is valid if its not null
         * (The path Class will not construct invalid path objects).
         */
        return path != null;
    }

    /**
     * This function converts the existing DVI output file generated by TeX to a PDF output file.
     * @return A boolean indicating whether the conversion was successful.
     */
    private boolean convertToPDF(){
        String DVIFile = this.outputFilePath.toString() + this.outputFileName + ".dvi";
        String[] cmds = {"dvipdfm", DVIFile};
        try {
            Process DVIPDFM = Runtime.getRuntime().exec(cmds);
            int exitVal = DVIPDFM.waitFor();
            return exitVal == 0;
        }catch(Exception e){
            return false;
        }
    }

    /**
     * This function deletes the existing DVI output file generated by TeX.
     * @return A boolean indicting whether the deletion was successful.
     */
    private boolean deleteDVIFile(){
        String DVIFile = this.outputFilePath.toString() + this.outputFileName + ".dvi";
        String[] cmds = {"rm", DVIFile};
        try {
            Process RM = Runtime.getRuntime().exec(cmds);
            int exitVal = RM.waitFor();
            return exitVal == 0;
        }catch(Exception e){
            return false;
        }
    }

    /**
     * This function deletes the existing log file generated by TeX.
     * @return A boolean indicting whether the deletion was successful.
     */
    private boolean deleteLogFile(){
        String logFile = this.outputFilePath.toString() + this.outputFileName + ".log";
        String[] cmds = {"rm", logFile};
        try {
            Process RM = Runtime.getRuntime().exec(cmds);
            int exitVal = RM.waitFor();
            return exitVal == 0;
        }catch(Exception e){
            return false;
        }
    }

    /**
     * This function builds the given TeXString.
     * @param source The TeXString to be built.
     * @return A boolean indicating whether the given TeXString was built successfully.
     */
    public boolean build(TeXString source) {
        if(source == null) return false;
        String fullFileName = this.outputFilePath.toString() + this.outputFileName;
        String[] cmds = {"tex", "-jobname=" + fullFileName, "\\relax", source.getSource(), "\\end"};
        boolean result = true;
        try {
            Process TeXProc = Runtime.getRuntime().exec(cmds);
            int exitVal = TeXProc.waitFor();
            if(exitVal != 0) result = false;
        }catch(Exception e){
            result = false;
        }

        if(pdf) if(!convertToPDF()) result = false;
        if(!log) if(!deleteLogFile()) result = false;
        if(!dvi) if(!deleteDVIFile()) result = false;

        return result;
    }

    /**
     * This function builds the given TeXFile.
     * @param source the TeXFile to be built.
     * @return A boolean indicating Whether the given TeXFile was built successfully.
     */
    public boolean build(TeXFile source){
        if(source == null) return false;
        String TeXFile = source.getPath().toString();
        String fullFileName = this.outputFilePath.toString() + this.outputFileName;
        String[] cmds = {"tex", "-jobname=" + fullFileName, TeXFile,"\\end"};
        boolean result = true;
        try {
            Process TeXProc = Runtime.getRuntime().exec(cmds);
            int exitVal = TeXProc.waitFor();
            if(exitVal != 0) result = false;
        }catch(Exception e){
            result = false;
        }

        if(pdf) if(!convertToPDF()) result = false;
        if(!log) if(!deleteLogFile()) result = false;
        if(!dvi) if(!deleteDVIFile()) result = false;

        return result;
    }
}
